import { createEntityRegistryState, type EntityRegistryState } from './entity';
import { ITEM_IDS, TOOL_IDS, type GameState, type InventoryState, type SaveData, type ToolId } from './types';
import { CURRENT_GENERATOR_VERSION, createInitialWorldSave, type WorldSaveData } from './world/world-save';
import type { ChunkPersistence } from './world/chunks';

export const SAVE_SCHEMA_VERSION = 5 as const;
const isObject = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null;
const isFiniteNonNegative = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value) && value >= 0;
const isFiniteInteger = (value: unknown): value is number => typeof value === 'number' && Number.isInteger(value) && Number.isFinite(value);
const isBoundedNumber = (value: unknown, min: number, max: number): value is number => typeof value === 'number' && Number.isFinite(value) && value >= min && value <= max;
const isInventory = (value: unknown): value is InventoryState => isObject(value) && ITEM_IDS.every((id) => isFiniteNonNegative(value[id]));
const isQuest = (value: unknown): boolean => isObject(value) && typeof value.id === 'string' && value.id.length > 0 && typeof value.title === 'string' && value.title.length > 0 && isFiniteInteger(value.need) && value.need > 0 && isFiniteInteger(value.progress) && value.progress >= 0 && value.progress <= value.need && isFiniteNonNegative(value.reward) && typeof value.done === 'boolean';
function isEntityRegistry(value: unknown): value is EntityRegistryState { if (!isObject(value) || !isObject(value.entities)) return false; if (!Object.entries(value.entities).every(([id, entity]) => id.length > 0 && isObject(entity) && entity.id === id && typeof entity.kind === 'string' && entity.kind.length > 0)) return false; const components = value.components; return components === undefined || (isObject(components) && Object.entries(components).every(([id, c]) => isObject(c) && id in value.entities && Object.values(c).every(isObject))); }
function isChunkPersistence(value: unknown): value is ChunkPersistence { if (!isObject(value) || typeof value.key !== 'string' || !isObject(value.modifiedTiles) || !isObject(value.removedEntities)) return false; return Object.values(value.modifiedTiles).every((m) => isObject(m) && typeof m.tile === 'string' && m.tile.length > 0) && Object.values(value.removedEntities).every((v) => v === true); }
function isWorldSave(value: unknown): value is WorldSaveData { if (!isObject(value)) return false; return isFiniteInteger(value.seed) && isFiniteInteger(value.generatorVersion) && value.generatorVersion >= 1 && isObject(value.chunks) && Object.values(value.chunks).every(isChunkPersistence) && isObject(value.crops) && Object.values(value.crops).every((c) => isObject(c) && isFiniteInteger(c.stage) && c.stage >= 0 && typeof c.watered === 'boolean' && typeof c.tilled === 'boolean') && isObject(value.removedResources) && Object.values(value.removedResources).every((t) => t === 'tree' || t === 'rock') && isEntityRegistry(value.entities); }
const isCalendar = (value: unknown): boolean => isObject(value) && isFiniteInteger(value.day) && value.day >= 1 && isFiniteNonNegative(value.clock) && isFiniteInteger(value.season) && value.season >= 0 && (value.weather === 'Sunny' || value.weather === 'Rainy' || value.weather === 'Cloudy');
const isPlayer = (value: unknown): value is GameState['player'] => isObject(value) && isFiniteNonNegative(value.x) && isFiniteNonNegative(value.y) && isBoundedNumber(value.health, 0, 100) && isBoundedNumber(value.stamina, 0, 100) && isBoundedNumber(value.hunger, 0, 100) && isFiniteNonNegative(value.money) && isFiniteInteger(value.pickaxeLevel) && value.pickaxeLevel >= 1 && typeof value.tool === 'string' && TOOL_IDS.includes(value.tool as ToolId);
const isEconomy = (value: unknown): boolean => isObject(value) && isFiniteNonNegative(value.fishCaught) && isFiniteNonNegative(value.shipped) && isFiniteNonNegative(value.totalHarvests);
const isPlayerSave = (value: unknown): value is SaveData['player'] => isObject(value) && isPlayer(value.player) && isInventory(value.inventory) && Array.isArray(value.quests) && value.quests.every(isQuest) && isEconomy(value.economy);
export function isGameState(value: unknown): value is GameState { return isObject(value) && isPlayer(value.player) && isInventory(value.inventory) && Array.isArray(value.quests) && value.quests.every(isQuest) && isCalendar(value.calendar) && isEconomy(value.economy); }
export function isSaveData(value: unknown): value is SaveData { return isObject(value) && value.schemaVersion === SAVE_SCHEMA_VERSION && isPlayerSave(value.player) && isCalendar(value.calendar) && isWorldSave(value.world); }
const defaultInventory = (): InventoryState => ({ wood: 12, stone: 10, ore: 8, crystal: 2, berry: 4, parsnip: 0, seeds: 6, torch: 6, sword: 1, fish: 0, coal: 3, rod: 0, salve: 0 });
function normalizeInventory(value: unknown): InventoryState { const result = defaultInventory(); if (!isObject(value)) return result; for (const id of ITEM_IDS) if (isFiniteNonNegative(value[id])) result[id] = value[id]; return result; }
function normalizeWorldEntities(value: unknown): EntityRegistryState { return isEntityRegistry(value) ? value : createEntityRegistryState(); }
function normalizeLegacyNumber(value: unknown, fallback: number, min = 0): number { return isFiniteNonNegative(value) && value >= min ? value : fallback; }
function migrateLegacyState(old: Record<string, unknown>): SaveData {
  const player = isObject(old.player) ? old.player : {}, calendar = isObject(old.calendar) ? old.calendar : {}, economy = isObject(old.economy) ? old.economy : {}, quests = Array.isArray(old.quests) ? old.quests : [], world = isObject(old.world) ? old.world : {}, legacyPlayer = !isObject(old.player) ? old : {};
  const read = (key: string, fallback: number, min = 0): number => normalizeLegacyNumber(player[key], normalizeLegacyNumber(legacyPlayer[key], fallback, min), min);
  const chunks: Record<string, ChunkPersistence> = isObject(world.chunks) ? Object.fromEntries(Object.entries(world.chunks).filter(([, c]) => isChunkPersistence(c))) as Record<string, ChunkPersistence> : {};
  const worldSave: WorldSaveData = { seed: isFiniteInteger(world.seed) ? world.seed : 2042, generatorVersion: isFiniteInteger(world.generatorVersion) && world.generatorVersion >= 1 ? world.generatorVersion : CURRENT_GENERATOR_VERSION, chunks, crops: isObject(world.crops) ? world.crops as WorldSaveData['crops'] : {}, removedResources: isObject(world.removedResources) ? world.removedResources as WorldSaveData['removedResources'] : {}, entities: normalizeWorldEntities(world.entities) };
  return { schemaVersion: SAVE_SCHEMA_VERSION, player: { player: { x: read('x', 35 * 24 + 12), y: read('y', 27 * 24 + 12), health: isBoundedNumber(player.health, 0, 100) ? player.health : 100, stamina: isBoundedNumber(player.stamina, 0, 100) ? player.stamina : 100, hunger: isBoundedNumber(player.hunger, 0, 100) ? player.hunger : 100, money: read('money', 120), pickaxeLevel: isFiniteInteger(player.pickaxeLevel) && player.pickaxeLevel >= 1 ? player.pickaxeLevel : 1, tool: typeof player.tool === 'string' && TOOL_IDS.includes(player.tool as ToolId) ? player.tool as ToolId : 'hoe' }, inventory: normalizeInventory(old.inventory), quests: quests.filter(isObject).map((q) => ({ id: String(q.id ?? 'quest'), title: String(q.title ?? 'Quest'), need: Math.max(1, Number(q.need) || 1), progress: Math.max(0, Number(q.progress) || 0), reward: Math.max(0, Number(q.reward) || 0), done: Boolean(q.done) })), economy: { fishCaught: isFiniteNonNegative(economy.fishCaught) ? economy.fishCaught : 0, shipped: isFiniteNonNegative(economy.shipped) ? economy.shipped : 0, totalHarvests: isFiniteNonNegative(economy.totalHarvests) ? economy.totalHarvests : 0 } }, calendar: { day: isFiniteInteger(calendar.day) && calendar.day >= 1 ? calendar.day : 1, clock: isFiniteNonNegative(calendar.clock) ? calendar.clock : 0, season: isFiniteInteger(calendar.season) && calendar.season >= 0 ? calendar.season : 0, weather: calendar.weather === 'Rainy' || calendar.weather === 'Cloudy' ? calendar.weather : 'Sunny' }, world: worldSave };
}
export function migrateSaveData(raw: unknown): SaveData | null { if (!isObject(raw)) return null; if (isSaveData(raw)) return raw; const schema = raw.schemaVersion; if (schema === 4 && isObject(raw.state)) return isObject(raw.state.world) && isWorldSave(raw.state.world) ? migrateLegacyState(raw.state) : null; if ((schema === 3 || schema === 2 || schema === 1) && isObject(raw.state)) return migrateLegacyState(raw.state); if (schema === undefined && 'inventory' in raw) return migrateLegacyState(raw); return null; }
export function migrateSave(raw: unknown): GameState | null { const save = migrateSaveData(raw); return save ? { player: save.player.player, inventory: save.player.inventory, quests: save.player.quests, calendar: save.calendar, economy: save.player.economy } : null; }
export function createSaveData(state: GameState, world: WorldSaveData): SaveData { if (!isGameState(state)) throw new Error('Cannot save invalid game state'); if (!isWorldSave(world)) throw new Error('Cannot save invalid world state'); return { schemaVersion: SAVE_SCHEMA_VERSION, player: { player: state.player, inventory: state.inventory, quests: state.quests, economy: state.economy }, calendar: state.calendar, world }; }
