import Phaser from 'phaser';

const VERSION='0.4.1';
const TILE=24,W=70,H=52,DAY_SECONDS=150;
type Tool='hoe'|'seeds'|'water'|'axe'|'pick'|'sword'|'rod';
type Item='wood'|'stone'|'ore'|'crystal'|'berry'|'parsnip'|'seeds'|'torch'|'sword'|'fish'|'coal'|'rod';
type RecipeId='copperPickaxe'|'sword'|'torch'|'healingSalve'|'fishingRod';
type Crop={stage:number,watered:boolean,tilled:boolean,g:Phaser.GameObjects.Graphics};
type Enemy={body:Phaser.GameObjects.Rectangle,hp:number,hit:number};
type Quest={id:string,title:string,need:number,progress:number,reward:number,done:boolean};
const RECIPES:Record<RecipeId,Partial<Record<Item,number>>>={copperPickaxe:{wood:8,ore:4},sword:{wood:4,ore:6},torch:{wood:2,coal:1},healingSalve:{berry:2,crystal:1},fishingRod:{wood:6,stone:2}};
const SAVE_KEY='core2d-save-v41';

class CozyFarm extends Phaser.Scene{
 private player!:Phaser.GameObjects.Rectangle; private cursors!:Phaser.Types.Input.Keyboard.CursorKeys; private keys!:Record<string,Phaser.Input.Keyboard.Key>;
 private crops=new Map<string,Crop>(); private trees:Phaser.GameObjects.Container[]=[]; private rocks:Phaser.GameObjects.Rectangle[]=[]; private enemies:Enemy[]=[]; private npcs:Phaser.GameObjects.Container[]=[];
 private day=1;private clock=0;private stamina=100;private hunger=100;private health=100;private money=120;private pickaxeLevel=1;private tool:Tool='hoe';private lastAction=0;private hud!:Phaser.GameObjects.Text;private message!:Phaser.GameObjects.Text;private night!:Phaser.GameObjects.Rectangle;private target!:Phaser.GameObjects.Rectangle;private paused=false;private fishCooldown=0;private weather='Sunny';private season=0;private fishCaught=0;private shipped=0;private totalHarvests=0;
 private inventory:Record<Item,number>={wood:12,ore:8,stone:10,berry:4,crystal:2,seeds:6,parsnip:0,torch:6,sword:1,fish:0,coal:3,rod:0};
 private quests:Quest[]=[{id:'harvest',title:'First Harvest',need:3,progress:0,reward:100,done:false},{id:'copper',title:'Copper Collector',need:10,progress:0,reward:150,done:false},{id:'fish',title:'River Friend',need:3,progress:0,reward:125,done:false}];
 constructor(){super('farm')}
 create(){const k=this.input.keyboard!;this.cursors=k.createCursorKeys();this.keys={W:k.addKey('W'),A:k.addKey('A'),S:k.addKey('S'),D:k.addKey('D'),SHIFT:k.addKey('SHIFT'),ONE:k.addKey('ONE'),TWO:k.addKey('TWO'),THREE:k.addKey('THREE'),FOUR:k.addKey('FOUR'),FIVE:k.addKey('FIVE'),SIX:k.addKey('SIX'),SEVEN:k.addKey('SEVEN'),E:k.addKey('E'),SPACE:k.addKey('SPACE'),F:k.addKey('F'),ESC:k.addKey('ESC'),B:k.addKey('B'),L:k.addKey('L'),Q:k.addKey('Q'),K:k.addKey('K'),P:k.addKey('P')};this.buildWorld();this.player=this.add.rectangle(35*TILE+12,27*TILE+12,14,19,0xf1cf91).setDepth(30);this.target=this.add.rectangle(0,0,TILE-2,TILE-2,0xffdf72,.18).setStrokeStyle(2,0xffdf72).setDepth(20);this.cameras.main.setBounds(0,0,W*TILE,H*TILE).startFollow(this.player,true,.12,.12).setZoom(1.3);this.night=this.add.rectangle(480,320,960,640,0x17243b,0).setScrollFactor(0).setDepth(90);this.hud=this.add.text(14,12,'',{fontFamily:'Georgia',fontSize:'15px',color:'#fff',backgroundColor:'#26351ddd',padding:{x:10,y:8}}).setScrollFactor(0).setDepth(100);this.message=this.add.text(480,14,'',{fontFamily:'Georgia',fontSize:'15px',color:'#ffe9ad',backgroundColor:'#26351ddd',padding:{x:10,y:7}}).setOrigin(.5,0).setScrollFactor(0).setDepth(100);this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{if(!this.paused&&p.leftButtonDown())this.actionAt(p.worldX,p.worldY)});window.addEventListener('core2d:craft',this.onCraft as EventListener);window.addEventListener('core2d:mine',this.onMine as EventListener);window.addEventListener('core2d:attack',this.onAttack as EventListener);window.addEventListener('core2d:place',this.onPlace as EventListener);window.addEventListener('core2d:select',this.onSelect as EventListener);window.addEventListener('core2d:eat',this.eat as EventListener);window.addEventListener('core2d:salve',this.salve as EventListener);window.addEventListener('core2d:sprint',this.sprint as EventListener);window.addEventListener('core2d:save',this.saveGame as EventListener);window.addEventListener('core2d:load',this.loadGame as EventListener);this.loadGame();this.say(`${this.seasonName()} • Day ${this.day} • Welcome home. Plant, fish, gather and explore.`);this.updateHud()}
 private buildWorld(){for(let y=0;y<H;y++)for(let x=0;x<W;x++){let c=(x+y)%2?0x6f9b4f:0x739f52;if(x>=27&&x<=43&&y>=19&&y<=35)c=(x+y)%2?0x9a6845:0xa06e4a;if(x>=53&&x<=64&&y>=19&&y<=35)c=(x+y)%3?0x77736c:0x88847b;this.add.rectangle(x*TILE+12,y*TILE+12,23,23,c)}this.add.ellipse(13*TILE,11*TILE,230,150,0x4f8fa3).setDepth(2).setStrokeStyle(4,0x315f70);this.add.text(10*TILE,8*TILE,'FISHING POND',{fontFamily:'Georgia',fontSize:'12px',color:'#fff0c2'}).setDepth(8);this.add.rectangle(35*TILE+12,17*TILE+12,12*TILE,6*TILE,0xc18a55).setDepth(5).setStrokeStyle(3,0x7b5537);this.add.polygon(35*TILE-133,17*TILE-43,[0,55,145,0,290,55],0x9a4e43).setDepth(6);this.add.text(35*TILE+12,17*TILE+5,'HOME',{fontFamily:'Georgia',fontSize:'13px',color:'#ffe6ad'}).setOrigin(.5).setDepth(7);this.add.text(58*TILE,18*TILE,'QUARRY',{fontFamily:'Georgia',fontSize:'13px',color:'#fff0c2'}).setDepth(8);this.add.text(7*TILE,36*TILE,'FOREST',{fontFamily:'Georgia',fontSize:'13px',color:'#fff0c2'}).setDepth(8);this.add.rectangle(49*TILE+12,29*TILE+12,3*TILE,2*TILE,0xb9794b).setDepth(5).setStrokeStyle(2,0x70462f);this.add.text(49*TILE+12,29*TILE+8,'MARKET',{fontFamily:'Georgia',fontSize:'11px',color:'#fff0c2'}).setOrigin(.5).setDepth(8);this.add.rectangle(45*TILE+12,35*TILE+12,2*TILE,2*TILE,0x8d6240).setDepth(5).setStrokeStyle(2,0x553b2a);this.add.text(45*TILE+12,35*TILE+8,'SHIP',{fontFamily:'Georgia',fontSize:'10px',color:'#fff0c2'}).setOrigin(.5).setDepth(8);this.add.rectangle(62*TILE+12,39*TILE+12,3*TILE,3*TILE,0x30263b).setDepth(4).setStrokeStyle(3,0x17121e);this.add.text(62*TILE+12,39*TILE+8,'CAVE',{fontFamily:'Georgia',fontSize:'11px',color:'#e8d4ff'}).setOrigin(.5).setDepth(8);
  for(let i=0;i<34;i++){const x=3+Math.floor(Math.random()*63),y=3+Math.floor(Math.random()*44);if(x>25&&x<46&&y>15&&y<37)continue;const c=this.add.container(x*TILE+12,y*TILE+12).setDepth(5);c.add(this.add.rectangle(0,10,11,22,0x60452e));c.add(this.add.circle(0,-5,17,0x355d3b));c.setData('x',x);c.setData('y',y);this.trees.push(c)}
  for(let i=0;i<24;i++){const x=54+Math.floor(Math.random()*10),y=20+Math.floor(Math.random()*15),r=this.add.rectangle(x*TILE+12,y*TILE+12,17,17,i%3===0?0xb7864f:0x77736c).setDepth(3);r.setData('x',x);r.setData('y',y);r.setData('ore',i%3===0);this.rocks.push(r)}
  for(let i=0;i<5;i++){const a=this.add.ellipse((22+i*2)*TILE+12,34*TILE+12,19,14,0xf1dfbd).setDepth(12);this.tweens.add({targets:a,y:a.y+3,duration:700+i*80,yoyo:true,repeat:-1})}
  const npc=this.add.container(47*TILE+12,31*TILE+12).setDepth(22);npc.add(this.add.circle(0,-8,8,0xd69b72));npc.add(this.add.rectangle(0,5,13,18,0x7c9b68));npc.add(this.add.text(0,20,'Mara',{fontFamily:'Georgia',fontSize:'10px',color:'#fff0c2'}).setOrigin(.5));npc.setData('type','npc');this.npcs.push(npc);
 }
 update(_t:number,delta:number){if(this.paused)return;const dt=Math.min(delta,50)/1000;this.clock+=dt;this.fishCooldown=Math.max(0,this.fishCooldown-dt);this.hunger=Math.max(0,this.hunger-dt*.10);this.stamina=Math.min(100,this.stamina+dt*(this.hunger<20?5:12));let dx=0,dy=0;if(this.cursors.left.isDown||this.keys.A.isDown)dx--;if(this.cursors.right.isDown||this.keys.D.isDown)dx++;if(this.cursors.up.isDown||this.keys.W.isDown)dy--;if(this.cursors.down.isDown||this.keys.S.isDown)dy++;const sprint=this.keys.SHIFT.isDown&&this.stamina>2;if(dx||dy){const l=Math.hypot(dx,dy),speed=sprint?230:145;const nx=Phaser.Math.Clamp(this.player.x+dx/l*speed*dt,10,W*TILE-10),ny=Phaser.Math.Clamp(this.player.y+dy/l*speed*dt,10,H*TILE-10);if(!this.blocked(nx,ny)){this.player.x=nx;this.player.y=ny}this.stamina=Math.max(0,this.stamina-dt*(sprint?12:3))}if(Phaser.Input.Keyboard.JustDown(this.keys.ONE))this.setTool('hoe');if(Phaser.Input.Keyboard.JustDown(this.keys.TWO))this.setTool('seeds');if(Phaser.Input.Keyboard.JustDown(this.keys.THREE))this.setTool('water');if(Phaser.Input.Keyboard.JustDown(this.keys.FOUR))this.setTool('axe');if(Phaser.Input.Keyboard.JustDown(this.keys.FIVE))this.setTool('pick');if(Phaser.Input.Keyboard.JustDown(this.keys.SIX))this.setTool('sword');if(Phaser.Input.Keyboard.JustDown(this.keys.SEVEN))this.setTool('rod');if(Phaser.Input.Keyboard.JustDown(this.keys.E))this.actionSelected();if(Phaser.Input.Keyboard.JustDown(this.keys.SPACE))this.eat();if(Phaser.Input.Keyboard.JustDown(this.keys.F))this.swing();if(Phaser.Input.Keyboard.JustDown(this.keys.B))this.buySeeds();if(Phaser.Input.Keyboard.JustDown(this.keys.L))this.shipItems();if(Phaser.Input.Keyboard.JustDown(this.keys.Q))this.showQuests();if(Phaser.Input.Keyboard.JustDown(this.keys.K))this.talkToNpc();if(Phaser.Input.Keyboard.JustDown(this.keys.P))this.saveGame();if(this.clock>=DAY_SECONDS)this.newDay();this.enemies.forEach(e=>this.updateEnemy(e,dt));this.spawnNightThreat();this.updateNight();this.selectedTarget();this.updateHud()}
 private blocked(x:number,y:number){const tx=Math.floor(x/TILE),ty=Math.floor(y/TILE);if(tx>=33&&tx<=37&&ty>=14&&ty<=20)return true;if(tx>=62&&tx<=64&&ty>=38&&ty<=40)return true;return false}
 private selectedTarget(){const x=Math.floor(this.player.x/TILE),y=Math.floor(this.player.y/TILE);this.target.setPosition(x*TILE+12,y*TILE+12)}
 private updateNight(){const phase=this.clock/DAY_SECONDS;const darkness=phase>.68?Math.min(.55,(phase-.68)/.18*.55):0;this.night.setAlpha(darkness)}
 private newDay(){this.clock-=DAY_SECONDS;this.day++;this.growCrops();this.weather=Math.random()<.22?'Rainy':Math.random()<.18?'Cloudy':'Sunny';this.stamina=100;this.health=Math.min(100,this.health+10);this.hunger=Math.max(0,this.hunger-6);this.saveGame();if(this.day%8===1)this.season=(this.season+1)%4;this.say(`${this.seasonName()} • Day ${this.day} • ${this.weather}. New morning!`)}
 private seasonName(){return ['Spring','Summer','Autumn','Winter'][this.season]}
 private setTool(t:Tool){this.tool=t;this.say(`${t.toUpperCase()} equipped • click nearby to use`)}
 private actionSelected(){this.actionAt(this.player.x,this.player.y)}
 private actionAt(wx:number,wy:number){if(this.time.now-this.lastAction<180)return;this.lastAction=this.time.now;const x=Math.floor(wx/TILE),y=Math.floor(wy/TILE);const px=Math.floor(this.player.x/TILE),py=Math.floor(this.player.y/TILE);if(Math.abs(x-px)>4||Math.abs(y-py)>4)return this.say('Too far away.');if(this.tool==='rod')return this.fish(x,y);switch(this.tool){case'hoe':this.hoe(x,y);break;case'seeds':this.plant(x,y);break;case'water':this.water(x,y);break;case'axe':this.chop(x,y);break;case'pick':this.mine(x,y);break;case'sword':this.swing()}}
 private plot(x:number,y:number){return x>=29&&x<=41&&y>=22&&y<=30}private k(x:number,y:number){return `${x},${y}`}
 private hoe(x:number,y:number){if(!this.plot(x,y))return this.say('Till soil inside the farm plot.');const key=this.k(x,y);if(this.crops.has(key))return this.say('That soil is already planted.');const g=this.add.graphics().setDepth(15);g.fillStyle(0x6b4b2f).fillRect(x*TILE+3,y*TILE+3,18,18);this.crops.set(key,{stage:0,watered:false,tilled:true,g});this.stamina=Math.max(0,this.stamina-4);this.say('Soil tilled. Plant a seed.')}
 private plant(x:number,y:number){if(!this.plot(x,y))return this.say('Plant inside the farm plot.');const key=this.k(x,y),c=this.crops.get(key);if(!c)return this.say('Till this tile first.');if(c.stage>0||c.watered)return this.say('A crop is already here.');if(this.inventory.seeds<1)return this.say('No seeds. Press B near home to buy some.');this.inventory.seeds--;c.stage=1;c.watered=false;c.g.fillStyle(0x6b4b2f).fillRect(x*TILE+3,y*TILE+3,18,18);c.g.fillStyle(0x70b85a).fillCircle(x*TILE+12,y*TILE+13,4);this.stamina=Math.max(0,this.stamina-2);this.say('Parsnip planted. Water it today.')}
 private water(x:number,y:number){const c=this.crops.get(this.k(x,y));if(!c||c.stage<1)return this.say('Plant a crop first.');if(c.watered)return this.say('Already watered today.');c.watered=true;c.g.fillStyle(0x70b85a).fillCircle(x*TILE+12,y*TILE+10,5);this.stamina=Math.max(0,this.stamina-1);this.say(this.weather==='Rainy'?'Rain is doing the work today.':'Crop watered.')}
 private growCrops(){for(const [key,c] of this.crops){if(c.stage>0&&c.watered)c.stage++;c.watered=false;const [x,y]=key.split(',').map(Number);c.g.clear();c.g.fillStyle(0x6b4b2f).fillRect(x*TILE+3,y*TILE+3,18,18);if(c.stage>0)c.g.fillStyle(c.stage>=4?0xffd45c:0x70b85a).fillCircle(x*TILE+12,y*TILE+10,5+c.stage)}}
 private harvest(x:number,y:number){const c=this.crops.get(this.k(x,y));if(!c||c.stage<4)return false;this.crops.delete(this.k(x,y));c.g.destroy();this.inventory.parsnip++;this.money+=35;this.totalHarvests++;const q=this.quests.find(q=>q.id==='harvest'&&!q.done);if(q)q.progress++;this.checkQuests();this.say('+1 Parsnip • +$35 • Harvest recorded');return true}
 private chop(x:number,y:number){const i=this.trees.findIndex(t=>t.getData('x')===x&&t.getData('y')===y);if(i<0)return this.say('No tree here.');this.trees[i].destroy();this.trees.splice(i,1);this.inventory.wood+=3;this.stamina=Math.max(0,this.stamina-8);this.say('+3 Wood.')}
 private mine(x:number,y:number){const i=this.rocks.findIndex(r=>r.getData('x')===x&&r.getData('y')===y);if(i<0)return this.say('Mine rocks in the quarry.');const r=this.rocks[i],ore=Boolean(r.getData('ore'));r.destroy();this.rocks.splice(i,1);const amount=ore?this.pickaxeLevel>=2?3:2:2;if(ore){this.inventory.ore+=amount;const q=this.quests.find(q=>q.id==='copper'&&!q.done);if(q)q.progress+=amount}else this.inventory.stone+=amount;this.stamina=Math.max(0,this.stamina-7);this.checkQuests();this.say(ore?`+${amount} Copper Ore.`:'+2 Stone.')}
 private fish(x:number,y:number){if(!this.inventory.rod)return this.say('Craft a Fishing Rod at the workbench first.');if(x>7&&x<20&&y>7&&y<15){if(this.fishCooldown>0)return this.say('Wait for a bite...');this.fishCooldown=2;this.inventory.fish++;this.fishCaught++;this.money+=25;const q=this.quests.find(q=>q.id==='fish'&&!q.done);if(q)q.progress++;this.checkQuests();this.say('You caught a river fish! +$25')}else this.say('Cast your rod at the pond.')}
 private buySeeds(){if(this.money<20)return this.say('The market costs $20 for 5 seeds.');this.money-=20;this.inventory.seeds+=5;this.say('Bought 5 seeds for $20.')}
 private shipItems(){const value=this.inventory.parsnip*35+this.inventory.fish*25+this.inventory.ore*8;const count=this.inventory.parsnip+this.inventory.fish+this.inventory.ore;if(!count)return this.say('Shipping bin is empty.');this.inventory.parsnip=0;this.inventory.fish=0;this.inventory.ore=0;this.money+=value;this.shipped+=count;this.say(`Shipped ${count} items • +$${value}`)}
 private talkToNpc(){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,47*TILE+12,31*TILE+12);if(d>70)return this.say('Mara is at the market.');this.say('Mara: “The valley is quiet tonight. Keep some berries for the road.”');if(this.inventory.berry>0){this.inventory.berry--;this.inventory.seeds++;this.say('Mara traded 1 berry for 1 seed.')}}
 private showQuests(){const q=this.quests.filter(q=>!q.done).map(q=>`${q.title}: ${q.progress}/${q.need} (+$${q.reward})`).join(' • ');this.say(q||'All current quests complete! More will arrive soon.')}
 private checkQuests(){for(const q of this.quests)if(!q.done&&q.progress>=q.need){q.done=true;this.money+=q.reward;this.say(`Quest complete: ${q.title}! +$${q.reward}`)}}
 private spawnNightThreat(){if(this.clock<DAY_SECONDS*.72||this.enemies.length>=3)return;if(Math.random()>0.0025)return;const x=58*TILE+12,y=34*TILE+12;const body=this.add.rectangle(x,y,18,18,0x8c6ad9).setDepth(25);this.enemies.push({body,hp:4,hit:0});this.say('A cave slime approaches!')}
 private swing(){if(!this.inventory.sword)return this.say('Craft a sword first.');const a=this.add.arc(this.player.x,this.player.y,48,-55,55,false,0xffe39a,.85).setDepth(40);this.tweens.add({targets:a,alpha:0,scale:1.5,duration:150,onComplete:()=>a.destroy()});this.cameras.main.shake(80,.002);this.stamina=Math.max(0,this.stamina-2);this.enemies.slice().forEach(e=>{if(Phaser.Math.Distance.Between(this.player.x,this.player.y,e.body.x,e.body.y)<=58){e.hp-=2;e.hit=.15;e.body.setFillStyle(0xffd6a0);if(e.hp<=0){e.body.destroy();this.enemies.splice(this.enemies.indexOf(e),1);this.inventory.ore+=1;this.say('+1 Ore • Slime defeated')}}})}
 private updateEnemy(e:Enemy,dt:number){e.hit=Math.max(0,e.hit-dt);if(e.hit===0)e.body.setFillStyle(0x8c6ad9);const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,e.body.x,e.body.y);if(d<180&&d>28){e.body.x+=(this.player.x-e.body.x)/d*24*dt;e.body.y+=(this.player.y-e.body.y)/d*24*dt}else if(d<=28&&e.hit===0){this.health=Math.max(0,this.health-8*dt);if(this.health<=0)this.respawn()}}
 private respawn(){this.health=70;this.player.setPosition(35*TILE+12,27*TILE+12);this.money=Math.max(0,this.money-20);this.say('You fainted and woke at home. -$20.')}
 private addDust(x:number,y:number){const g=this.add.graphics().setDepth(35);g.fillStyle(0xe7c27f,.8);for(let i=0;i<5;i++)g.fillCircle(x*TILE+Phaser.Math.Between(4,20),y*TILE+Phaser.Math.Between(4,20),2);this.tweens.add({targets:g,alpha:0,duration:250,onComplete:()=>g.destroy()})}
 private onCraft=(e:Event)=>{const id=(e as CustomEvent).detail?.id as RecipeId;const cost=RECIPES[id];if(!cost)return;const missing=Object.entries(cost).find(([it,n])=>(this.inventory[it as Item]??0)<(n??0));if(missing)return this.say(`Not enough ${missing[0]}.`);for(const [it,n] of Object.entries(cost))this.inventory[it as Item]-=n??0;if(id==='copperPickaxe')this.pickaxeLevel=2;if(id==='sword')this.inventory.sword=1;if(id==='torch')this.inventory.torch+=3;if(id==='healingSalve'){this.health=Math.min(100,this.health+35);this.say('Healing Salve used • +35 health.')}if(id==='fishingRod')this.inventory.rod=1;this.updateHud();this.say(`${id} crafted.`)}
 private onMine=()=>this.actionAt(this.player.x,this.player.y);private onAttack=()=>this.swing();private onPlace=()=>{const x=Math.floor(this.player.x/TILE),y=Math.floor(this.player.y/TILE);if(this.tool==='seeds')return this.plant(x,y);if(this.tool==='hoe')return this.hoe(x,y);if(this.tool==='water')return this.water(x,y);if(this.harvest(x,y))return;this.actionSelected()};private onSelect=(e:Event)=>{const slot=(e as CustomEvent).detail?.slot??0;const tools:Tool[]=['sword','hoe','seeds','water','axe','pick','rod'];if(slot>=0&&slot<tools.length)this.setTool(tools[slot])};private eat=()=>{if(this.inventory.berry<1)return this.say('No berries.');this.inventory.berry--;this.hunger=Math.min(100,this.hunger+25);this.health=Math.min(100,this.health+5);this.say('Berry eaten • +25 hunger.')};private salve=()=>this.onCraft(new CustomEvent('core2d:craft',{detail:{id:'healingSalve'}}));private sprint=()=>this.say('Sprint: hold Shift while moving.');
 private saveGame=()=>{try{const data={day:this.day,clock:this.clock,stamina:this.stamina,hunger:this.hunger,health:this.health,money:this.money,pickaxeLevel:this.pickaxeLevel,inventory:this.inventory,quests:this.quests,season:this.season,weather:this.weather,fishCaught:this.fishCaught,shipped:this.shipped,totalHarvests:this.totalHarvests};localStorage.setItem(SAVE_KEY,JSON.stringify(data));this.say('Game saved.')}catch{this.say('Save unavailable in this browser.')}};
 private loadGame=()=>{try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return;const d=JSON.parse(raw);this.day=d.day??1;this.clock=d.clock??0;this.stamina=d.stamina??100;this.hunger=d.hunger??100;this.health=d.health??100;this.money=d.money??120;this.pickaxeLevel=d.pickaxeLevel??1;this.inventory={...this.inventory,...(d.inventory??{})};this.quests=d.quests??this.quests;this.season=d.season??0;this.weather=d.weather??'Sunny';this.fishCaught=d.fishCaught??0;this.shipped=d.shipped??0;this.totalHarvests=d.totalHarvests??0}catch{this.say('Starting a fresh farm.')}};
 private updateHud(){const phase=this.clock/DAY_SECONDS;const hh=Math.floor(6+phase*14),mm=Math.floor((phase*14*60)%60);const time=`${String(hh).padStart(2,'0')}:${String(mm).padStart(2,'0')}`;const active=this.quests.filter(q=>!q.done)[0];this.hud.setText(`CORE2D v${VERSION}  •  ${this.seasonName()} ${this.day}  •  ${time}\n♥ ${Math.ceil(this.health)}  🍓 ${Math.ceil(this.hunger)}  ⚡ ${Math.ceil(this.stamina)}  •  $${this.money}\n🪵 ${this.inventory.wood}  ◆ ${this.inventory.ore}  🪨 ${this.inventory.stone}  🌱 ${this.inventory.seeds}  🐟 ${this.inventory.fish}  🎣 ${this.inventory.rod}\nTool: ${this.tool.toUpperCase()}  •  Quest: ${active?`${active.title} ${active.progress}/${active.need}`:'All complete!'}`);window.dispatchEvent(new CustomEvent('core2d:state',{detail:{version:VERSION,health:this.health,hunger:this.hunger,stamina:this.stamina,pickaxeLevel:this.pickaxeLevel,survivalTime:this.clock,threats:this.enemies.length,selectedSlot:['sword','hoe','seeds','water','axe','pick','rod'].indexOf(this.tool),inventory:{...this.inventory},inventoryCapacity:24,attackRange:2.3,hasSword:Boolean(this.inventory.sword)}}))}
 private say(text:string){if(this.message)this.message.setText(text);window.dispatchEvent(new CustomEvent('core2d:message',{detail:{text}}))}
}

export default CozyFarm;
