import Phaser from 'phaser';

const VERSION='0.3.22';
const TILE=24,W=70,H=52,DAY_SECONDS=150;
type Tool='hoe'|'seeds'|'water'|'axe'|'pick'|'sword';
type Item='wood'|'stone'|'ore'|'crystal'|'berry'|'parsnip'|'seeds'|'torch'|'sword';
type RecipeId='copperPickaxe'|'sword'|'torch'|'healingSalve';
type Crop={stage:number,watered:boolean,g:Phaser.GameObjects.Graphics};
type Enemy={body:Phaser.GameObjects.Rectangle,hp:number,hit:number};
const RECIPES:Record<RecipeId,Partial<Record<Item,number>>>={copperPickaxe:{wood:8,ore:4},sword:{wood:4,ore:6},torch:{wood:2,ore:1},healingSalve:{berry:2,crystal:1}};

class CozyFarm extends Phaser.Scene{
 private player!:Phaser.GameObjects.Rectangle; private cursors!:Phaser.Types.Input.Keyboard.CursorKeys; private keys!:Record<string,Phaser.Input.Keyboard.Key>;
 private crops=new Map<string,Crop>(); private trees:Phaser.GameObjects.Container[]=[]; private rocks:Phaser.GameObjects.Rectangle[]=[]; private enemies:Enemy[]=[]; private solids:Phaser.GameObjects.GameObject[]=[];
 private day=1;private clock=0;private stamina=100;private hunger=100;private health=100;private money=120;private pickaxeLevel=1;private tool:Tool='hoe';private lastAction=0;private hud!:Phaser.GameObjects.Text;private message!:Phaser.GameObjects.Text;private night!:Phaser.GameObjects.Rectangle;private target!:Phaser.GameObjects.Rectangle;private paused=false;
 private inventory:Record<Item,number>={wood:12,ore:8,stone:10,berry:4,crystal:2,seeds:6,parsnip:0,torch:6,sword:1};
 constructor(){super('farm')}
 create(){const k=this.input.keyboard!;this.cursors=k.createCursorKeys();this.keys={W:k.addKey('W'),A:k.addKey('A'),S:k.addKey('S'),D:k.addKey('D'),SHIFT:k.addKey('SHIFT'),ONE:k.addKey('ONE'),TWO:k.addKey('TWO'),THREE:k.addKey('THREE'),FOUR:k.addKey('FOUR'),FIVE:k.addKey('FIVE'),SIX:k.addKey('SIX'),E:k.addKey('E'),SPACE:k.addKey('SPACE'),F:k.addKey('F'),ESC:k.addKey('ESC')};this.buildWorld();this.player=this.add.rectangle(35*TILE+12,27*TILE+12,14,19,0xf1cf91).setDepth(30);this.target=this.add.rectangle(0,0,TILE-2,TILE-2,0xffdf72,.18).setStrokeStyle(2,0xffdf72).setDepth(20);this.cameras.main.setBounds(0,0,W*TILE,H*TILE).startFollow(this.player,true,.12,.12).setZoom(1.3);this.night=this.add.rectangle(480,320,960,640,0x17243b,0).setScrollFactor(0).setDepth(90);this.hud=this.add.text(14,12,'',{fontFamily:'Georgia',fontSize:'15px',color:'#fff',backgroundColor:'#26351ddd',padding:{x:10,y:8}}).setScrollFactor(0).setDepth(100);this.message=this.add.text(480,14,'',{fontFamily:'Georgia',fontSize:'15px',color:'#ffe9ad',backgroundColor:'#26351ddd',padding:{x:10,y:7}}).setOrigin(.5,0).setScrollFactor(0).setDepth(100);this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{if(!this.paused&&p.leftButtonDown())this.actionAt(p.worldX,p.worldY)});window.addEventListener('core2d:craft',this.onCraft as EventListener);window.addEventListener('core2d:mine',this.onMine as EventListener);window.addEventListener('core2d:attack',this.onAttack as EventListener);window.addEventListener('core2d:place',this.onPlace as EventListener);window.addEventListener('core2d:select',this.onSelect as EventListener);window.addEventListener('core2d:eat',this.eat as EventListener);window.addEventListener('core2d:salve',this.salve as EventListener);window.addEventListener('core2d:sprint',this.sprint as EventListener);this.say('Day 1 • Farm your crops, gather wood, then explore the quarry.');this.updateHud()}
 private buildWorld(){for(let y=0;y<H;y++)for(let x=0;x<W;x++){let c=0x6f9b4f;if(x>=27&&x<=43&&y>=19&&y<=35)c=0x9a6845;if(x>=53&&x<=64&&y>=19&&y<=35)c=(x+y)%3?0x77736c:0x88847b;this.add.rectangle(x*TILE+12,y*TILE+12,23,23,c)}this.add.ellipse(13*TILE,11*TILE,230,150,0x4f8fa3).setDepth(2).setStrokeStyle(4,0x315f70);this.add.rectangle(35*TILE+12,17*TILE+12,12*TILE,6*TILE,0xc18a55).setDepth(5).setStrokeStyle(3,0x7b5537);this.add.polygon(35*TILE-133,17*TILE-43,[0,55,145,0,290,55],0x9a4e43).setDepth(6);this.add.text(35*TILE+12,17*TILE+5,'HOME',{fontFamily:'Georgia',fontSize:'13px',color:'#ffe6ad'}).setOrigin(.5).setDepth(7);this.add.text(58*TILE,18*TILE,'QUARRY',{fontFamily:'Georgia',fontSize:'13px',color:'#fff0c2'}).setDepth(8);this.add.text(7*TILE,36*TILE,'FOREST',{fontFamily:'Georgia',fontSize:'13px',color:'#fff0c2'}).setDepth(8);
  for(let i=0;i<32;i++){const x=3+Math.floor(Math.random()*63),y=3+Math.floor(Math.random()*44);if(x>25&&x<46&&y>15&&y<37)continue;const c=this.add.container(x*TILE+12,y*TILE+12).setDepth(5);c.add(this.add.rectangle(0,10,11,22,0x60452e));c.add(this.add.circle(0,-5,17,0x355d3b));c.setData('x',x);c.setData('y',y);this.trees.push(c)}
  for(let i=0;i<20;i++){const x=54+Math.floor(Math.random()*10),y=20+Math.floor(Math.random()*15),r=this.add.rectangle(x*TILE+12,y*TILE+12,17,17,i%3===0?0xb7864f:0x77736c).setDepth(3);r.setData('x',x);r.setData('y',y);r.setData('ore',i%3===0);this.rocks.push(r)}
  for(let i=0;i<5;i++){const a=this.add.ellipse((22+i*2)*TILE+12,34*TILE+12,19,14,0xf1dfbd).setDepth(12);this.tweens.add({targets:a,y:a.y+3,duration:700+i*80,yoyo:true,repeat:-1})}
 }
 update(_t:number,delta:number){if(this.paused)return;const dt=Math.min(delta,50)/1000;this.clock+=dt;this.hunger=Math.max(0,this.hunger-dt*.12);this.stamina=Math.min(100,this.stamina+dt*(this.hunger<20?6:12));let dx=0,dy=0;if(this.cursors.left.isDown||this.keys.A.isDown)dx--;if(this.cursors.right.isDown||this.keys.D.isDown)dx++;if(this.cursors.up.isDown||this.keys.W.isDown)dy--;if(this.cursors.down.isDown||this.keys.S.isDown)dy++;const sprint=(this.keys.SHIFT.isDown&&this.stamina>2);if(dx||dy){const l=Math.hypot(dx,dy),speed=sprint?230:145;const nx=Phaser.Math.Clamp(this.player.x+dx/l*speed*dt,10,W*TILE-10),ny=Phaser.Math.Clamp(this.player.y+dy/l*speed*dt,10,H*TILE-10);if(!this.blocked(nx,ny)){this.player.x=nx;this.player.y=ny}this.stamina=Math.max(0,this.stamina-dt*(sprint?12:3))}if(Phaser.Input.Keyboard.JustDown(this.keys.ONE))this.setTool('hoe');if(Phaser.Input.Keyboard.JustDown(this.keys.TWO))this.setTool('seeds');if(Phaser.Input.Keyboard.JustDown(this.keys.THREE))this.setTool('water');if(Phaser.Input.Keyboard.JustDown(this.keys.FOUR))this.setTool('axe');if(Phaser.Input.Keyboard.JustDown(this.keys.FIVE))this.setTool('pick');if(Phaser.Input.Keyboard.JustDown(this.keys.SIX))this.setTool('sword');if(Phaser.Input.Keyboard.JustDown(this.keys.E))this.actionSelected();if(Phaser.Input.Keyboard.JustDown(this.keys.SPACE))this.eat();if(Phaser.Input.Keyboard.JustDown(this.keys.F))this.swing();if(this.clock>=DAY_SECONDS)this.newDay();this.enemies.forEach(e=>this.updateEnemy(e,dt));this.selectedTarget();this.updateHud()}
 private blocked(x:number,y:number){const tx=Math.floor(x/TILE),ty=Math.floor(y/TILE);return tx>=33&&tx<=37&&ty>=14&&ty<=20}
 private selectedTarget(){const x=Math.floor(this.player.x/TILE),y=Math.floor(this.player.y/TILE);this.target.setPosition(x*TILE+12,y*TILE+12)}
 private newDay(){this.clock-=DAY_SECONDS;this.day++;this.growCrops();this.stamina=100;this.health=Math.min(100,this.health+5);this.hunger=Math.max(0,this.hunger-8);this.say(`Day ${this.day} • Morning. Crops grew overnight.`)}
 private setTool(t:Tool){this.tool=t;this.say(`${t.toUpperCase()} equipped • click nearby to use`)}
 private actionSelected(){this.actionAt(this.player.x,this.player.y)}
 private actionAt(wx:number,wy:number){if(this.time.now-this.lastAction<180)return;this.lastAction=this.time.now;const x=Math.floor(wx/TILE),y=Math.floor(wy/TILE);const px=Math.floor(this.player.x/TILE),py=Math.floor(this.player.y/TILE);if(Math.abs(x-px)>4||Math.abs(y-py)>4)return this.say('Too far away.');switch(this.tool){case'hoe':this.hoe(x,y);break;case'seeds':this.plant(x,y);break;case'water':this.water(x,y);break;case'axe':this.chop(x,y);break;case'pick':this.mine(x,y);break;case'sword':this.swing()}}
 private plot(x:number,y:number){return x>=29&&x<=41&&y>=22&&y<=30}private k(x:number,y:number){return `${x},${y}`}
 private hoe(x:number,y:number){if(!this.plot(x,y))return this.say('Till soil inside the farm plot.');this.stamina=Math.max(0,this.stamina-4);this.addDust(x,y);this.say('Soil tilled. Plant a seed.')}
 private plant(x:number,y:number){if(!this.plot(x,y))return this.say('Plant inside the farm plot.');const key=this.k(x,y);if(this.crops.has(key))return this.say('A crop is already here.');if(this.inventory.seeds<1)return this.say('No seeds. Buy seeds at the market.');this.inventory.seeds--;const g=this.add.graphics().setDepth(15);g.fillStyle(0x6b4b2f).fillCircle(x*TILE+12,y*TILE+15,4);this.crops.set(key,{stage:0,watered:false,g});this.stamina=Math.max(0,this.stamina-2);this.say('Parsnip planted. Water it today.')}
 private water(x:number,y:number){const c=this.crops.get(this.k(x,y));if(!c)return this.say('Water a planted crop.');if(c.watered)return this.say('Already watered today.');c.watered=true;c.g.clear().fillStyle(0x70b85a).fillCircle(x*TILE+12,y*TILE+10,5);this.stamina=Math.max(0,this.stamina-1);this.say('Crop watered.')}
 private growCrops(){for(const [key,c] of this.crops){if(c.watered)c.stage++;c.watered=false;const [x,y]=key.split(',').map(Number);c.g.clear().fillStyle(c.stage>=3?0xffd45c:0x70b85a).fillCircle(x*TILE+12,y*TILE+10,5+c.stage)}}
 private harvest(x:number,y:number){const c=this.crops.get(this.k(x,y));if(!c||c.stage<3)return false;this.crops.delete(this.k(x,y));c.g.destroy();this.inventory.parsnip++;this.money+=35;this.say('+1 Parsnip • +$35');return true}
 private chop(x:number,y:number){const i=this.trees.findIndex(t=>t.getData('x')===x&&t.getData('y')===y);if(i<0)return this.say('No tree here.');this.trees[i].destroy();this.trees.splice(i,1);this.inventory.wood+=3;this.stamina=Math.max(0,this.stamina-8);this.say('+3 Wood.')}
 private mine(x:number,y:number){const i=this.rocks.findIndex(r=>r.getData('x')===x&&r.getData('y')===y);if(i<0)return this.say('Mine rocks in the quarry.');const r=this.rocks[i],ore=Boolean(r.getData('ore'));r.destroy();this.rocks.splice(i,1);const amount=ore?this.pickaxeLevel>=2?3:2:2;if(ore)this.inventory.ore+=amount;else this.inventory.stone+=amount;this.stamina=Math.max(0,this.stamina-7);this.say(ore?`+${amount} Copper Ore.`:'+2 Stone.')}
 private swing(){if(!this.inventory.sword)return this.say('Craft a sword first.');const a=this.add.arc(this.player.x,this.player.y,48,-55,55,false,0xffe39a,.85).setDepth(40);this.tweens.add({targets:a,alpha:0,scale:1.5,duration:150,onComplete:()=>a.destroy()});this.cameras.main.shake(80,0.002);this.stamina=Math.max(0,this.stamina-2);const range=58;this.enemies.slice().forEach(e=>{if(Phaser.Math.Distance.Between(this.player.x,this.player.y,e.body.x,e.body.y)<=range){e.hp-=2;e.hit=0.15;e.body.setFillStyle(0xffd6a0);if(e.hp<=0){e.body.destroy();this.enemies.splice(this.enemies.indexOf(e),1);this.inventory.ore+=1;this.say('+1 Ore • Slime defeated.')}}});}
 private updateEnemy(e:Enemy,dt:number){e.hit=Math.max(0,e.hit-dt);if(e.hit===0)e.body.setFillStyle(0x8c6ad9);const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,e.body.x,e.body.y);if(d<180&&d>28){e.body.x+=(this.player.x-e.body.x)/d*24*dt;e.body.y+=(this.player.y-e.body.y)/d*24*dt}else if(d<=28&&e.hit===0){this.health=Math.max(0,this.health-8*dt);if(this.health<=0)this.respawn()}}
 private spawnEnemy(){const x=60*TILE+12,y=34*TILE+12;const body=this.add.rectangle(x,y,18,18,0x8c6ad9).setDepth(25);this.enemies.push({body,hp:4,hit:0});this.say('A cave slime approaches!')}
 private respawn(){this.health=70;this.player.setPosition(35*TILE+12,27*TILE+12);this.money=Math.max(0,this.money-20);this.say('You fainted and woke at home. -$20.')}
 private addDust(x:number,y:number){const g=this.add.graphics().setDepth(35);g.fillStyle(0xe7c27f,.8);for(let i=0;i<5;i++)g.fillCircle(x*TILE+Phaser.Math.Between(4,20),y*TILE+Phaser.Math.Between(4,20),2);this.tweens.add({targets:g,alpha:0,duration:250,onComplete:()=>g.destroy()})}
 private onCraft=(e:Event)=>{const id=(e as CustomEvent).detail?.id as RecipeId;const cost=RECIPES[id];if(!cost)return;const missing=Object.entries(cost).find(([it,n])=>(this.inventory[it as Item]??0)<(n??0));if(missing)return this.say(`Not enough ${missing[0]}.`);for(const [it,n] of Object.entries(cost))this.inventory[it as Item]-=n??0;if(id==='copperPickaxe')this.pickaxeLevel=2;if(id==='sword')this.inventory.sword=1;if(id==='torch')this.inventory.torch+=3;if(id==='healingSalve')this.salve();else this.say('Crafted successfully.')}
 private onMine=()=>{this.setTool('pick');this.actionSelected()};private onAttack=()=>this.swing();private onPlace=()=>this.actionSelected();private onSelect=(e:Event)=>{const s=Number((e as CustomEvent).detail?.slot),map:Tool[]=['sword','axe','pick','pick','seeds','water'];if(Number.isFinite(s)&&map[s])this.setTool(map[s])};private eat=()=>{if(!this.inventory.berry)return this.say('No berries.');this.inventory.berry--;this.hunger=Math.min(100,this.hunger+30);this.health=Math.min(100,this.health+6);this.say('Berry eaten.')};private salve=()=>{if(this.inventory.berry<2||this.inventory.crystal<1)return this.say('Need 2 berries + 1 crystal.');this.inventory.berry-=2;this.inventory.crystal--;this.health=Math.min(100,this.health+30);this.say('Healing salve used. +30 health.')};private sprint=()=>{if(this.stamina<20)return this.say('Too tired to sprint.');this.stamina-=20;this.tweens.add({targets:this.player,scaleX:1.35,duration:70,yoyo:true});this.say('Sprint!')};
 private onPlaceAction(){if(this.plot(Math.floor(this.player.x/TILE),Math.floor(this.player.y/TILE)))this.harvest(Math.floor(this.player.x/TILE),Math.floor(this.player.y/TILE))}
 private updateHud(){const h=Math.floor(this.clock/DAY_SECONDS*24),m=Math.floor((this.clock/DAY_SECONDS*24%1)*60);window.dispatchEvent(new CustomEvent('core2d:state',{detail:{version:VERSION,health:this.health,hunger:this.hunger,stamina:this.stamina,pickaxeLevel:this.pickaxeLevel,survivalTime:(this.day-1)*DAY_SECONDS+this.clock,threats:this.enemies.length,selectedSlot:['sword','axe','pick','pick','seeds','water'].indexOf(this.tool),inventory:{...this.inventory},inventoryCapacity:24,attackRange:2.4,hasSword:Boolean(this.inventory.sword)}}));this.hud.setText(`DAY ${this.day}  ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}\n♥ ${Math.ceil(this.health)}   Hunger ${Math.ceil(this.hunger)}   Stamina ${Math.ceil(this.stamina)}\n$ ${this.money}   ${this.tool.toUpperCase()}  Pick Lv.${this.pickaxeLevel}`)}
 private say(text:string){this.message.setText(text);window.dispatchEvent(new CustomEvent('core2d:message',{detail:{text}}))}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',width:960,height:640,backgroundColor:'#5f8749',pixelArt:true,scene:[CozyFarm]});
