import './ui.css';
const VERSION='0.3.4';
type Item='wood'|'ore'|'stone'|'crystal'|'berry'|'torch'|'sword'; type RecipeId='copperPickaxe'|'sword'|'torch'|'healingSalve';
type State={version:string;health:number;hunger:number;stamina:number;pickaxeLevel:number;survivalTime:number;threats:number;selectedSlot:number;inventory:Partial<Record<Item,number>>;inventoryCapacity:number;attackRange:number;hasSword:boolean};
const items:Record<Item,{name:string;icon:string}>={wood:{name:'WOOD',icon:'🪵'},stone:{name:'STONE',icon:'🪨'},ore:{name:'COPPER',icon:'◆'},crystal:{name:'CRYSTAL',icon:'✦'},berry:{name:'BERRY',icon:'🍓'},torch:{name:'TORCH',icon:'🔥'},sword:{name:'SWORD',icon:'⚔'}};
const recipes:Array<{id:RecipeId;icon:string;name:string;cost:Partial<Record<Item,number>>;action:string}>= [{id:'copperPickaxe',icon:'⛏',name:'Copper Pickaxe',cost:{wood:8,ore:4},action:'CRAFT'},{id:'sword',icon:'⚔',name:'Copper Sword',cost:{wood:4,ore:6},action:'CRAFT'},{id:'torch',icon:'🔥',name:'Torch ×3',cost:{wood:2,ore:1},action:'CRAFT'},{id:'healingSalve',icon:'✚',name:'Healing Salve',cost:{berry:2,crystal:1},action:'MAKE + USE'}];
const root=document.createElement('div');root.id='core-ui';root.innerHTML=`<header class="ui-top"><div class="ui-brand"><span class="brand-title">CORE2D</span><span class="brand-version">v${VERSION}</span></div><div class="ui-stats"><div class="stat health"><span>HEALTH</span><strong data-value="health">100 / 100</strong><div class="bar"><i data-fill="health"></i></div></div><div class="stat hunger"><span>ENERGY</span><strong data-value="hunger">100 / 100</strong><div class="bar"><i data-fill="hunger"></i></div></div><div class="stat stamina"><span>STAMINA</span><strong data-value="stamina">100 / 100</strong><div class="bar"><i data-fill="stamina"></i></div></div></div></header>
<div class="ui-message" id="ui-message">A quiet morning beneath the surface.</div><aside class="ui-journal"><div class="journal-tab">DAY 1</div><h3>Journal</h3><div class="journal-note" id="ui-situation">Gather materials and prepare before pushing deeper.</div><h4>TO-DO</h4><div class="todo">○ Gather materials</div><div class="todo">○ Craft a Pickaxe</div><div class="todo">○ Craft a Sword</div><div class="journal-divider"></div><div class="small-stat">PICKAXE <b id="ui-pickaxe">Lv.1</b></div><div class="small-stat">SWORD <b id="ui-sword">NOT CRAFTED</b></div><div class="small-stat">RANGE <b id="ui-range">2.3 tiles</b></div><div class="small-stat">SURVIVAL <b id="ui-time">00:00</b></div><div class="small-stat danger">THREATS <b id="ui-threats">1</b></div></aside>
<div class="ui-action-dock"><div class="dock-label">TOOLS</div><button class="tool-btn primary" id="ui-attack"><span>⚔</span><b>Sword Attack</b><em>Left click / F • 2.3 tile range</em></button><button class="tool-btn" id="ui-mine"><span>⛏</span><b>Mine</b><em>Click selected tile</em></button><button class="tool-btn" id="ui-place"><span>▣</span><b>Place</b><em>Selected hotbar item</em></button><button class="tool-btn" id="ui-sprint"><span>➜</span><b>Sprint</b><em>Quick dash</em></button><div class="dock-row"><button class="tool-btn mini" id="ui-eat"><span>🍓</span><b>Eat</b></button><button class="tool-btn mini" id="ui-salve"><span>✚</span><b>Salve</b></button></div></div>
<div class="ui-bottom"><div class="hotbar-wrap"><div class="hotbar-label">QUICK BAR</div><div class="hotbar" id="hotbar"></div></div><div class="controls"><span>WASD</span> Move &nbsp; <span>LMB</span> Attack/Mine &nbsp; <span>F</span> Attack &nbsp; <span>I</span> Backpack</div></div>
<nav class="ui-nav"><button class="ui-button" id="ui-inventory-button">BACKPACK <kbd>I</kbd></button><button class="ui-button" id="ui-craft-button">CRAFT <kbd>C</kbd></button><button class="ui-button" id="ui-help-button">MENU <kbd>?</kbd></button></nav>
<div class="ui-inventory" id="ui-inventory"><div class="menu-card inventory-card"><div class="menu-ribbon">BACKPACK</div><div class="menu-head"><div><h2>Inventory</h2><p id="inventory-summary">24 slots</p></div><button class="menu-close" id="ui-inventory-close">×</button></div><div class="inventory-grid" id="inventory-grid"></div><div class="menu-footer">Click a stack to select it. Your quick bar is slots 1–6.</div></div></div>
<div class="ui-crafting" id="ui-crafting"><div class="menu-card"><div class="menu-ribbon">WORKBENCH</div><div class="menu-head"><div><h2>Crafting</h2><p>Tools, weapons and supplies for the expedition.</p></div><button class="menu-close" id="ui-craft-close">×</button></div><div class="craft-grid" id="craft-grid"></div><div class="menu-footer">Craft the Copper Sword, select it in the quick bar, then slash with the mouse or F.</div></div></div>
<div class="ui-help" id="ui-help"><div class="menu-card small"><div class="menu-ribbon">PAUSE MENU</div><div class="menu-head"><div><h2>Core2D</h2><p>Take a breath. Your expedition is waiting.</p></div><button class="menu-close" id="ui-help-close">×</button></div><div class="menu-actions"><button id="menu-inventory">Open Backpack</button><button id="menu-craft">Open Crafting</button><button id="menu-close">Back to game</button></div><div class="help-list"><div><b>Move</b><span>W A S D / Arrows</span></div><div><b>Attack</b><span>Left click / F with Sword equipped</span></div><div><b>Attack range</b><span>2.3 tiles, cone-shaped hit</span></div><div><b>Mine</b><span>Left click with another item selected</span></div><div><b>Inventory</b><span>I or Backpack button</span></div></div></div></div>`;document.body.appendChild(root);
const hotbar=document.querySelector<HTMLDivElement>('#hotbar')!,message=document.querySelector<HTMLDivElement>('#ui-message')!,crafting=document.querySelector<HTMLDivElement>('#ui-crafting')!,craftGrid=document.querySelector<HTMLDivElement>('#craft-grid')!,help=document.querySelector<HTMLDivElement>('#ui-help')!,inventory=document.querySelector<HTMLDivElement>('#ui-inventory')!,inventoryGrid=document.querySelector<HTMLDivElement>('#inventory-grid')!,situation=document.querySelector<HTMLDivElement>('#ui-situation')!;
let latestState:State={version:VERSION,health:100,hunger:100,stamina:100,pickaxeLevel:1,survivalTime:0,threats:1,selectedSlot:0,inventory:{wood:6,berry:2},inventoryCapacity:24,attackRange:2.25,hasSword:false};
const formatTime=(s:number)=>{const t=Math.floor(s);return `${Math.floor(t/60).toString().padStart(2,'0')}:${(t%60).toString().padStart(2,'0')}`};
const slots:Item[]=['sword','wood','stone','ore','berry','torch'];
const renderHotbar=()=>{hotbar.innerHTML=slots.map((item,i)=>`<button class="slot ${i===latestState.selectedSlot?'selected':''}" data-slot="${i}"><span class="slot-key">${i+1}</span><span class="slot-icon">${items[item].icon}</span><span class="slot-name">${items[item].name}</span><span class="slot-count">${latestState.inventory[item]??0}</span></button>`).join('');hotbar.querySelectorAll<HTMLButtonElement>('[data-slot]').forEach(b=>b.onclick=()=>window.dispatchEvent(new CustomEvent('core2d:select',{detail:{slot:Number(b.dataset.slot)}})))};
const renderInventory=()=>{const all:Object=latestState.inventory;const list=(Object.keys(items) as Item[]);inventoryGrid.innerHTML=Array.from({length:latestState.inventoryCapacity},(_,i)=>{const item=list[i];const count=item?(latestState.inventory[item]??0):0;return item&&count>0?`<button class="inv-slot filled" data-item="${item}"><span>${items[item].icon}</span><b>${items[item].name}</b><em>${count}</em></button>`:`<div class="inv-slot"><span>·</span><small>${i+1}</small></div>`}).join('');document.querySelector('#inventory-summary')!.textContent=`${Object.values(all).filter(v=>(v??0)>0).length} / ${latestState.inventoryCapacity} item stacks`};
const renderCrafting=()=>{craftGrid.innerHTML=recipes.map(r=>{const locked=r.id==='healingSalve'&&latestState.pickaxeLevel<2;const enough=Object.entries(r.cost).every(([it,n])=>(latestState.inventory[it as Item]??0)>=n);const built=(r.id==='copperPickaxe'&&latestState.pickaxeLevel>=2)||(r.id==='sword'&&latestState.hasSword);const disabled=locked||!enough||built;const costs=Object.entries(r.cost).map(([it,n])=>`${n} ${items[it as Item].name}`).join(' · ');return `<div class="recipe"><div class="recipe-icon">${r.icon}</div><div class="recipe-info"><b>${r.name}</b><small>${locked?'Requires Copper Pickaxe':costs}</small></div><button class="recipe-button" data-recipe="${r.id}" ${disabled?'disabled':''}>${locked?'LOCKED':built?'BUILT':r.action}</button></div>`}).join('');craftGrid.querySelectorAll<HTMLButtonElement>('[data-recipe]').forEach(b=>b.onclick=()=>window.dispatchEvent(new CustomEvent('core2d:craft',{detail:{id:b.dataset.recipe}})))};
const setBar=(n:string,v:number,m:number)=>{const e=document.querySelector<HTMLElement>(`[data-value="${n}"]`),f=document.querySelector<HTMLElement>(`[data-fill="${n}"]`);if(e)e.textContent=`${Math.ceil(v)} / ${m}`;if(f)f.style.width=`${Math.max(0,Math.min(100,v/m*100))}%`};
const updateSituation=()=>{if(!latestState.hasSword)situation.textContent='A sword would make exploring safer. Craft one with 4 Wood + 6 Copper Ore.';else if(latestState.health<=25)situation.textContent='Critical health. Use a salve or retreat to the Core.';else if(latestState.hunger<=20)situation.textContent='Low energy. Eat a Berry before you run dry.';else situation.textContent='Sword ready. Keep enemies inside the short attack cone and strike from range.'};
window.addEventListener('core2d:state',e=>{latestState={...latestState,...(e as CustomEvent<State>).detail};setBar('health',latestState.health,100);setBar('hunger',latestState.hunger,100);setBar('stamina',latestState.stamina,100);document.querySelector('#ui-pickaxe')!.textContent=`Lv.${latestState.pickaxeLevel}`;document.querySelector('#ui-sword')!.textContent=latestState.hasSword?'READY':'NOT CRAFTED';document.querySelector('#ui-range')!.textContent=`${latestState.attackRange.toFixed(1)} tiles`;document.querySelector('#ui-time')!.textContent=formatTime(latestState.survivalTime);document.querySelector('#ui-threats')!.textContent=String(latestState.threats);updateSituation();renderHotbar();renderInventory();renderCrafting()});
window.addEventListener('core2d:message',e=>{const t=(e as CustomEvent<{text?:string}>).detail?.text;if(t)message.textContent=t});
const toggle=(el:HTMLElement)=>el.classList.toggle('open'); const closeMenus=()=>{help.classList.remove('open');crafting.classList.remove('open');inventory.classList.remove('open')};
document.querySelector('#ui-attack')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('core2d:attack',{detail:{dx:1,dy:0}})));document.querySelector('#ui-mine')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('core2d:mine')));document.querySelector('#ui-place')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('core2d:place')));document.querySelector('#ui-sprint')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('core2d:sprint')));document.querySelector('#ui-eat')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('core2d:eat')));document.querySelector('#ui-salve')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('core2d:salve')));
document.querySelector('#ui-inventory-button')?.addEventListener('click',()=>toggle(inventory));document.querySelector('#ui-inventory-close')?.addEventListener('click',()=>inventory.classList.remove('open'));inventory.addEventListener('click',e=>{if(e.target===inventory)inventory.classList.remove('open')});
document.querySelector('#ui-craft-button')?.addEventListener('click',()=>toggle(crafting));document.querySelector('#ui-craft-close')?.addEventListener('click',()=>crafting.classList.remove('open'));crafting.addEventListener('click',e=>{if(e.target===crafting)crafting.classList.remove('open')});
document.querySelector('#ui-help-button')?.addEventListener('click',()=>help.classList.add('open'));document.querySelector('#ui-help-close')?.addEventListener('click',closeMenus);document.querySelector('#menu-close')?.addEventListener('click',closeMenus);document.querySelector('#menu-craft')?.addEventListener('click',()=>{help.classList.remove('open');crafting.classList.add('open')});document.querySelector('#menu-inventory')?.addEventListener('click',()=>{help.classList.remove('open');inventory.classList.add('open')});help.addEventListener('click',e=>{if(e.target===help)help.classList.remove('open')});window.addEventListener('keydown',e=>{if(e.key==='?'||(e.shiftKey&&e.key==='/'))help.classList.add('open');if(e.key==='Escape')closeMenus()});
renderHotbar();renderInventory();renderCrafting();updateSituation();console.info(`[Core2D UI] v${VERSION} combat + backpack loaded`);
