import './ui.css';

const VERSION = '0.3.3';
type Item = 'wood' | 'ore' | 'stone' | 'crystal' | 'berry' | 'torch';
type RecipeId = 'copperPickaxe' | 'torch' | 'healingSalve';
type State = { version:string; health:number; hunger:number; stamina:number; pickaxeLevel:number; survivalTime:number; threats:number; selectedSlot:number; inventory:Partial<Record<Item,number>> };
const items:Record<Item,{name:string;icon:string}>={wood:{name:'WOOD',icon:'🪵'},stone:{name:'STONE',icon:'🪨'},ore:{name:'COPPER',icon:'◆'},crystal:{name:'CRYSTAL',icon:'✦'},berry:{name:'BERRY',icon:'🍓'},torch:{name:'TORCH',icon:'🔥'}};
const recipes:Array<{id:RecipeId;icon:string;name:string;cost:Partial<Record<Item,number>>;action:string}>=[{id:'copperPickaxe',icon:'⛏',name:'Copper Pickaxe',cost:{wood:8,ore:4},action:'CRAFT'},{id:'torch',icon:'🔥',name:'Torch ×3',cost:{wood:2,ore:1},action:'CRAFT'},{id:'healingSalve',icon:'✚',name:'Healing Salve',cost:{berry:2,crystal:1},action:'MAKE + USE'}];
const root=document.createElement('div');root.id='core-ui';root.innerHTML=`
<header class="ui-top"><div class="ui-brand"><span class="brand-title">CORE2D</span><span class="brand-version">v${VERSION}</span></div><div class="ui-stats"><div class="stat health"><span>HEALTH</span><strong data-value="health">100 / 100</strong><div class="bar"><i data-fill="health"></i></div></div><div class="stat hunger"><span>ENERGY</span><strong data-value="hunger">100 / 100</strong><div class="bar"><i data-fill="hunger"></i></div></div><div class="stat stamina"><span>STAMINA</span><strong data-value="stamina">100 / 100</strong><div class="bar"><i data-fill="stamina"></i></div></div></div></header>
<div class="ui-message" id="ui-message">A quiet morning beneath the surface.</div>
<aside class="ui-journal"><div class="journal-tab">DAY 1</div><h3>Journal</h3><div class="journal-note" id="ui-situation">Gather materials and prepare before pushing deeper.</div><h4>TO-DO</h4><div class="todo"><span>○</span> Gather 8 Wood</div><div class="todo"><span>○</span> Find 4 Copper Ore</div><div class="todo"><span>○</span> Craft a Pickaxe</div><div class="journal-divider"></div><div class="small-stat">PICKAXE <b id="ui-pickaxe">Lv.1</b></div><div class="small-stat">SURVIVAL <b id="ui-time">00:00</b></div><div class="small-stat danger">THREATS <b id="ui-threats">1</b></div></aside>
<div class="ui-action-dock"><div class="dock-label">TOOLS</div><button class="tool-btn primary" id="ui-mine"><span>⛏</span><b>Mine / Attack</b><em>Click selected tile</em></button><button class="tool-btn" id="ui-place"><span>▣</span><b>Place</b><em>Selected hotbar item</em></button><button class="tool-btn" id="ui-sprint"><span>➜</span><b>Sprint</b><em>Quick dash</em></button><div class="dock-row"><button class="tool-btn mini" id="ui-eat"><span>🍓</span><b>Eat</b></button><button class="tool-btn mini" id="ui-salve"><span>✚</span><b>Salve</b></button></div></div>
<div class="ui-bottom"><div class="hotbar-wrap"><div class="hotbar-label">BACKPACK</div><div class="hotbar" id="hotbar"></div></div><div class="controls"><span>WASD</span> Move &nbsp; <span>LMB</span> Mine &nbsp; <span>C</span> Craft &nbsp; <span>ESC</span> Menu</div></div>
<nav class="ui-nav"><button class="ui-button" id="ui-craft-button">CRAFT <kbd>C</kbd></button><button class="ui-button" id="ui-help-button">MENU <kbd>?</kbd></button></nav>
<div class="ui-crafting" id="ui-crafting"><div class="menu-card"><div class="menu-ribbon">WORKBENCH</div><div class="menu-head"><div><h2>Crafting</h2><p>Turn gathered materials into useful tools and supplies.</p></div><button class="menu-close" id="ui-craft-close">×</button></div><div class="craft-grid" id="craft-grid"></div><div class="menu-footer">Tip: the Copper Pickaxe unlocks Healing Salves.</div></div></div>
<div class="ui-help" id="ui-help"><div class="menu-card small"><div class="menu-ribbon">PAUSE MENU</div><div class="menu-head"><div><h2>Core2D</h2><p>Take a breath. Your expedition is waiting.</p></div><button class="menu-close" id="ui-help-close">×</button></div><div class="menu-actions"><button id="menu-craft">Open Crafting</button><button id="menu-close">Back to game</button></div><div class="help-list"><div><b>Move</b><span>W A S D / Arrows</span></div><div><b>Mine / Attack</b><span>Left click or Mine button</span></div><div><b>Place</b><span>Place button</span></div><div><b>Eat / Salve</b><span>SPACE / Q or buttons</span></div><div><b>Inventory</b><span>1 — 6 or click a slot</span></div></div></div></div>`;
document.body.appendChild(root);
const hotbar=document.querySelector<HTMLDivElement>('#hotbar')!,message=document.querySelector<HTMLDivElement>('#ui-message')!,crafting=document.querySelector<HTMLDivElement>('#ui-crafting')!,craftGrid=document.querySelector<HTMLDivElement>('#craft-grid')!,help=document.querySelector<HTMLDivElement>('#ui-help')!,situation=document.querySelector<HTMLDivElement>('#ui-situation')!;
let latestState:State={version:VERSION,health:100,hunger:100,stamina:100,pickaxeLevel:1,survivalTime:0,threats:1,selectedSlot:0,inventory:{wood:6,berry:2}};
const formatTime=(seconds:number)=>{const total=Math.floor(seconds);return `${Math.floor(total/60).toString().padStart(2,'0')}:${(total%60).toString().padStart(2,'0')}`};
const renderHotbar=()=>{const slots:Item[]=['wood','stone','ore','crystal','berry','torch'];hotbar.innerHTML=slots.map((item,index)=>`<button class="slot ${index===latestState.selectedSlot?'selected':''}" data-slot="${index}" title="Select ${items[item].name}"><span class="slot-key">${index+1}</span><span class="slot-icon">${items[item].icon}</span><span class="slot-name">${items[item].name}</span><span class="slot-count">${latestState.inventory[item]??0}</span></button>`).join('');hotbar.querySelectorAll<HTMLButtonElement>('[data-slot]').forEach(button=>button.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('core2d:select',{detail:{slot:Number(button.dataset.slot)}}))))};
const renderCrafting=()=>{craftGrid.innerHTML=recipes.map(recipe=>{const locked=recipe.id==='healingSalve'&&latestState.pickaxeLevel<2;const enough=Object.entries(recipe.cost).every(([item,amount])=>(latestState.inventory[item as Item]??0)>=amount);const disabled=locked||!enough||(recipe.id==='copperPickaxe'&&latestState.pickaxeLevel>=2);const costs=Object.entries(recipe.cost).map(([item,amount])=>`${amount} ${items[item as Item].name}`).join(' · ');const label=locked?'LOCKED':recipe.id==='copperPickaxe'&&latestState.pickaxeLevel>=2?'BUILT':recipe.action;return `<div class="recipe"><div class="recipe-icon">${recipe.icon}</div><div class="recipe-info"><b>${recipe.name}</b><small>${locked?'Requires Copper Pickaxe':costs}</small></div><button class="recipe-button" data-recipe="${recipe.id}" ${disabled?'disabled':''}>${label}</button></div>`}).join('');craftGrid.querySelectorAll<HTMLButtonElement>('[data-recipe]').forEach(button=>button.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('core2d:craft',{detail:{id:button.dataset.recipe}}))))};
const setBar=(name:string,value:number,max:number)=>{const valueEl=document.querySelector<HTMLElement>(`[data-value="${name}"]`),fill=document.querySelector<HTMLElement>(`[data-fill="${name}"]`);if(valueEl)valueEl.textContent=`${Math.ceil(value)} / ${max}`;if(fill)fill.style.width=`${Math.max(0,Math.min(100,value/max*100))}%`};
const updateSituation=()=>{if(latestState.health<=25)situation.textContent='Critical health. Use a salve or retreat to the Core.';else if(latestState.hunger<=20)situation.textContent='Low energy. Eat a Berry before you run dry.';else if(latestState.threats>=4)situation.textContent='Creatures are gathering. Keep moving and choose your fights.';else if(latestState.pickaxeLevel<2)situation.textContent='Gather 8 Wood + 4 Copper Ore to make your first Pickaxe.';else situation.textContent='Your Copper Pickaxe is ready. Push deeper and bring Torches.'};
window.addEventListener('core2d:state',event=>{latestState={...latestState,...(event as CustomEvent<State>).detail};setBar('health',latestState.health,100);setBar('hunger',latestState.hunger,100);setBar('stamina',latestState.stamina,100);document.querySelector('#ui-pickaxe')!.textContent=`Lv.${latestState.pickaxeLevel}`;document.querySelector('#ui-time')!.textContent=formatTime(latestState.survivalTime);document.querySelector('#ui-threats')!.textContent=String(latestState.threats);updateSituation();renderHotbar();renderCrafting()});
window.addEventListener('core2d:message',event=>{const text=(event as CustomEvent<{text?:string}>).detail?.text;if(text)message.textContent=text});
const toggleCrafting=()=>crafting.classList.toggle('open');
const openHelp=()=>help.classList.add('open');
const closeMenus=()=>{help.classList.remove('open');crafting.classList.remove('open')};
document.querySelector('#ui-mine')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('core2d:mine')));
document.querySelector('#ui-place')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('core2d:place')));
document.querySelector('#ui-sprint')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('core2d:sprint')));
document.querySelector('#ui-eat')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('core2d:eat')));
document.querySelector('#ui-salve')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('core2d:salve')));
document.querySelector('#ui-craft-button')?.addEventListener('click',toggleCrafting);document.querySelector('#ui-craft-close')?.addEventListener('click',()=>crafting.classList.remove('open'));crafting.addEventListener('click',event=>{if(event.target===crafting)crafting.classList.remove('open')});
document.querySelector('#ui-help-button')?.addEventListener('click',openHelp);document.querySelector('#ui-help-close')?.addEventListener('click',closeMenus);document.querySelector('#menu-close')?.addEventListener('click',closeMenus);document.querySelector('#menu-craft')?.addEventListener('click',()=>{help.classList.remove('open');crafting.classList.add('open')});help.addEventListener('click',event=>{if(event.target===help)help.classList.remove('open')});
window.addEventListener('keydown',event=>{if(event.key==='?'||(event.shiftKey&&event.key==='/'))openHelp();if(event.key==='Escape')closeMenus()});
renderHotbar();renderCrafting();updateSituation();console.info(`[Core2D UI] v${VERSION} Stardew-inspired journal HUD loaded`);
